# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import patient_detail_pb2 as patient__detail__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in patient_detail_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PatientDetailServiceStub(object):
    """gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientDetails = channel.unary_unary(
                '/patient.PatientDetailService/GetPatientDetails',
                request_serializer=patient__detail__pb2.GetPatientDetailsRequest.SerializeToString,
                response_deserializer=patient__detail__pb2.GetPatientDetailsResponse.FromString,
                _registered_method=True)
        self.UpdatePatientDetails = channel.unary_unary(
                '/patient.PatientDetailService/UpdatePatientDetails',
                request_serializer=patient__detail__pb2.UpdatePatientDetailsRequest.SerializeToString,
                response_deserializer=patient__detail__pb2.UpdatePatientDetailsResponse.FromString,
                _registered_method=True)
        self.UpdateMedicalRecords = channel.unary_unary(
                '/patient.PatientDetailService/UpdateMedicalRecords',
                request_serializer=patient__detail__pb2.UpdateMedicalRecordsRequest.SerializeToString,
                response_deserializer=patient__detail__pb2.UpdateMedicalRecordsResponse.FromString,
                _registered_method=True)
        self.CreatePatient = channel.unary_unary(
                '/patient.PatientDetailService/CreatePatient',
                request_serializer=patient__detail__pb2.CreatePatientRequest.SerializeToString,
                response_deserializer=patient__detail__pb2.CreatePatientResponse.FromString,
                _registered_method=True)
        self.InsertPatientRecords = channel.unary_unary(
                '/patient.PatientDetailService/InsertPatientRecords',
                request_serializer=patient__detail__pb2.InsertPatientRecordsRequest.SerializeToString,
                response_deserializer=patient__detail__pb2.InsertPatientRecordsResponse.FromString,
                _registered_method=True)


class PatientDetailServiceServicer(object):
    """gRPC service
    """

    def GetPatientDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatientDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMedicalRecords(self, request, context):
        """New methods for updating medical records
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePatient(self, request, context):
        """Create a new patient with medical records
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertPatientRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientDetailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientDetails,
                    request_deserializer=patient__detail__pb2.GetPatientDetailsRequest.FromString,
                    response_serializer=patient__detail__pb2.GetPatientDetailsResponse.SerializeToString,
            ),
            'UpdatePatientDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatientDetails,
                    request_deserializer=patient__detail__pb2.UpdatePatientDetailsRequest.FromString,
                    response_serializer=patient__detail__pb2.UpdatePatientDetailsResponse.SerializeToString,
            ),
            'UpdateMedicalRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMedicalRecords,
                    request_deserializer=patient__detail__pb2.UpdateMedicalRecordsRequest.FromString,
                    response_serializer=patient__detail__pb2.UpdateMedicalRecordsResponse.SerializeToString,
            ),
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=patient__detail__pb2.CreatePatientRequest.FromString,
                    response_serializer=patient__detail__pb2.CreatePatientResponse.SerializeToString,
            ),
            'InsertPatientRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertPatientRecords,
                    request_deserializer=patient__detail__pb2.InsertPatientRecordsRequest.FromString,
                    response_serializer=patient__detail__pb2.InsertPatientRecordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'patient.PatientDetailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('patient.PatientDetailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientDetailService(object):
    """gRPC service
    """

    @staticmethod
    def GetPatientDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientDetailService/GetPatientDetails',
            patient__detail__pb2.GetPatientDetailsRequest.SerializeToString,
            patient__detail__pb2.GetPatientDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePatientDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientDetailService/UpdatePatientDetails',
            patient__detail__pb2.UpdatePatientDetailsRequest.SerializeToString,
            patient__detail__pb2.UpdatePatientDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMedicalRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientDetailService/UpdateMedicalRecords',
            patient__detail__pb2.UpdateMedicalRecordsRequest.SerializeToString,
            patient__detail__pb2.UpdateMedicalRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientDetailService/CreatePatient',
            patient__detail__pb2.CreatePatientRequest.SerializeToString,
            patient__detail__pb2.CreatePatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertPatientRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/patient.PatientDetailService/InsertPatientRecords',
            patient__detail__pb2.InsertPatientRecordsRequest.SerializeToString,
            patient__detail__pb2.InsertPatientRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
