syntax = "proto3";

package patient;

// gRPC service
service PatientDetailService {
  rpc GetPatientDetails (GetPatientDetailsRequest) returns (GetPatientDetailsResponse);
}

// Request
message GetPatientDetailsRequest {
  int32 patient_id = 1;
}

// Response
message GetPatientDetailsResponse {
  Patient patient = 1;
  repeated GeneralInformation general_info = 2;
  repeated DiabetesInformation diabetes_info = 3;
  repeated HMODInformation hmod_info = 4;
  repeated CKDInformation ckd_info = 5;
  repeated CVDInformation cvd_info = 6;
}

// === Entity Messages ===

message Patient {
  int32 patient_id = 1;
  string name = 2;
  int32 age = 3;
  int32 gender = 4;
  float diabetes = 5;
  float hmod = 6;
  float ckd = 7;
  float cvd = 8;
  float chd = 9;
  string risk_category_id = 10;
  string risk_description = 11;
}

message GeneralInformation {
  int32 info_id = 1;
  int32 pid = 2;
  int32 avg_daily_steps = 3;
  int32 hdl = 4;
  int32 ldl = 5;
  float cholesterol = 6;
  int32 cacs = 7;
  int32 resting_pulse = 8;
  string test_date = 9;
}

message DiabetesInformation {
  int32 diabetes_id = 1;
  int32 pid = 2;
  int32 fbg = 3;
  float hba1c = 4;
  string test_date = 5;
}

message HMODInformation {
  int32 hmod_id = 1;
  int32 pid = 2;
  int32 lv_mass = 3;
  int32 microalbuminuria = 4;
  float pwv = 5;
  float abi = 6;
  string test_date = 7;
}

message CKDInformation {
  int32 ckd_id = 1;
  int32 pid = 2;
  float serum_creatinine = 3;
  int32 egfr = 4;
  int32 uacr = 5;
  string test_date = 6;
}

message CVDInformation {
  int32 cvd_id = 1;
  int32 pid = 2;
  string bp = 3;
  int32 smoking = 4;
  string test_date = 5;
}
