apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: list-patient-service-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: list-patient-service
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 15
  pollingInterval: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: "http://host.docker.internal:9090"
      metricName: "patient_list_requests_total"
      query: "sum(rate(patient_list_requests_total[15s]))"
      threshold: "5"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
