apiVersion: v1
kind: Service
metadata:
  name: list-patient-service
spec:
  type: NodePort   # Exposes the service outside the cluster
  selector:
    app: list-patient-service
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
      nodePort: 30052  # optional: pick port to access outside
    - name: metrics
      port: 8001
      targetPort: 8001
      nodePort: 30081
