apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-patient-service
  template:
    metadata:
      labels:
        app: list-patient-service
    spec:
      containers:
        - name: list-patient-service
          image: list-patient-service:latest
          imagePullPolicy: Never # Use "Never" if you're loading the image locally via `minikube image load` or `kind load docker-image`
          ports:
            - containerPort: 50052
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: "host.docker.internal"  # ⬅️ Points to Docker Compose
            - name: DB_PORT
              value: "3309"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "pass123"
            - name: DB_NAME
              value: "Project"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
