# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'risk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrisk.proto\x12\x04risk\"7\n\rSubmitRequest\x12\x0f\n\x07site_id\x18\x01 \x01(\t\x12\x15\n\rfeatures_json\x18\x02 \x01(\t\"$\n\x0eSubmitResponse\x12\x12\n\npatient_id\x18\x01 \x01(\t\" \n\nGetRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"m\n\x0bGetResponse\x12\r\n\x05probs\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x0f\n\x07site_id\x18\x03 \x01(\t\x12\x12\n\nrisk_group\x18\x04 \x01(\t\x12\x16\n\x0e\x64isease_groups\x18\x05 \x01(\t2v\n\x0bRiskService\x12\x37\n\nSubmitRisk\x12\x13.risk.SubmitRequest\x1a\x14.risk.SubmitResponse\x12.\n\x07GetRisk\x12\x10.risk.GetRequest\x1a\x11.risk.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITREQUEST']._serialized_start=20
  _globals['_SUBMITREQUEST']._serialized_end=75
  _globals['_SUBMITRESPONSE']._serialized_start=77
  _globals['_SUBMITRESPONSE']._serialized_end=113
  _globals['_GETREQUEST']._serialized_start=115
  _globals['_GETREQUEST']._serialized_end=147
  _globals['_GETRESPONSE']._serialized_start=149
  _globals['_GETRESPONSE']._serialized_end=258
  _globals['_RISKSERVICE']._serialized_start=260
  _globals['_RISKSERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
