# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import risk_pb2 as risk__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in risk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRisk = channel.unary_unary(
                '/risk.RiskService/SubmitRisk',
                request_serializer=risk__pb2.SubmitRequest.SerializeToString,
                response_deserializer=risk__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.GetRisk = channel.unary_unary(
                '/risk.RiskService/GetRisk',
                request_serializer=risk__pb2.GetRequest.SerializeToString,
                response_deserializer=risk__pb2.GetResponse.FromString,
                _registered_method=True)


class RiskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRisk,
                    request_deserializer=risk__pb2.SubmitRequest.FromString,
                    response_serializer=risk__pb2.SubmitResponse.SerializeToString,
            ),
            'GetRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRisk,
                    request_deserializer=risk__pb2.GetRequest.FromString,
                    response_serializer=risk__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'risk.RiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('risk.RiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/risk.RiskService/SubmitRisk',
            risk__pb2.SubmitRequest.SerializeToString,
            risk__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/risk.RiskService/GetRisk',
            risk__pb2.GetRequest.SerializeToString,
            risk__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
