/**
 * @fileoverview gRPC-Web generated client stub for patient
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: list_patient.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.patient = require('./list_patient_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.patient.PatientServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.patient.PatientServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.patient.ListPatientsRequest,
 *   !proto.patient.ListPatientsResponse>}
 */
const methodDescriptor_PatientService_ListPatients = new grpc.web.MethodDescriptor(
  '/patient.PatientService/ListPatients',
  grpc.web.MethodType.UNARY,
  proto.patient.ListPatientsRequest,
  proto.patient.ListPatientsResponse,
  /**
   * @param {!proto.patient.ListPatientsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.patient.ListPatientsResponse.deserializeBinary
);


/**
 * @param {!proto.patient.ListPatientsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.patient.ListPatientsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.patient.ListPatientsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.patient.PatientServiceClient.prototype.listPatients =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/patient.PatientService/ListPatients',
      request,
      metadata || {},
      methodDescriptor_PatientService_ListPatients,
      callback);
};


/**
 * @param {!proto.patient.ListPatientsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.patient.ListPatientsResponse>}
 *     Promise that resolves to the response
 */
proto.patient.PatientServicePromiseClient.prototype.listPatients =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/patient.PatientService/ListPatients',
      request,
      metadata || {},
      methodDescriptor_PatientService_ListPatients);
};


module.exports = proto.patient;

