/**
 * @fileoverview gRPC-Web generated client stub for scheduler
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: doctor.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.scheduler = require('./doctor_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.scheduler.SchedulerServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.scheduler.SchedulerServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.scheduler.Empty,
 *   !proto.scheduler.DoctorList>}
 */
const methodDescriptor_SchedulerService_GetDoctors = new grpc.web.MethodDescriptor(
  '/scheduler.SchedulerService/GetDoctors',
  grpc.web.MethodType.UNARY,
  proto.scheduler.Empty,
  proto.scheduler.DoctorList,
  /**
   * @param {!proto.scheduler.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.scheduler.DoctorList.deserializeBinary
);


/**
 * @param {!proto.scheduler.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.scheduler.DoctorList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.scheduler.DoctorList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.scheduler.SchedulerServiceClient.prototype.getDoctors =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/scheduler.SchedulerService/GetDoctors',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_GetDoctors,
      callback);
};


/**
 * @param {!proto.scheduler.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.scheduler.DoctorList>}
 *     Promise that resolves to the response
 */
proto.scheduler.SchedulerServicePromiseClient.prototype.getDoctors =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/scheduler.SchedulerService/GetDoctors',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_GetDoctors);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.scheduler.DoctorAvailabilityRequest,
 *   !proto.scheduler.DoctorAvailabilityList>}
 */
const methodDescriptor_SchedulerService_GetAvailability = new grpc.web.MethodDescriptor(
  '/scheduler.SchedulerService/GetAvailability',
  grpc.web.MethodType.UNARY,
  proto.scheduler.DoctorAvailabilityRequest,
  proto.scheduler.DoctorAvailabilityList,
  /**
   * @param {!proto.scheduler.DoctorAvailabilityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.scheduler.DoctorAvailabilityList.deserializeBinary
);


/**
 * @param {!proto.scheduler.DoctorAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.scheduler.DoctorAvailabilityList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.scheduler.DoctorAvailabilityList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.scheduler.SchedulerServiceClient.prototype.getAvailability =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/scheduler.SchedulerService/GetAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_GetAvailability,
      callback);
};


/**
 * @param {!proto.scheduler.DoctorAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.scheduler.DoctorAvailabilityList>}
 *     Promise that resolves to the response
 */
proto.scheduler.SchedulerServicePromiseClient.prototype.getAvailability =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/scheduler.SchedulerService/GetAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_GetAvailability);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.scheduler.UpdateAvailabilityRequest,
 *   !proto.scheduler.UpdateAvailabilityResponse>}
 */
const methodDescriptor_SchedulerService_UpdateAvailability = new grpc.web.MethodDescriptor(
  '/scheduler.SchedulerService/UpdateAvailability',
  grpc.web.MethodType.UNARY,
  proto.scheduler.UpdateAvailabilityRequest,
  proto.scheduler.UpdateAvailabilityResponse,
  /**
   * @param {!proto.scheduler.UpdateAvailabilityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.scheduler.UpdateAvailabilityResponse.deserializeBinary
);


/**
 * @param {!proto.scheduler.UpdateAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.scheduler.UpdateAvailabilityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.scheduler.UpdateAvailabilityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.scheduler.SchedulerServiceClient.prototype.updateAvailability =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/scheduler.SchedulerService/UpdateAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_UpdateAvailability,
      callback);
};


/**
 * @param {!proto.scheduler.UpdateAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.scheduler.UpdateAvailabilityResponse>}
 *     Promise that resolves to the response
 */
proto.scheduler.SchedulerServicePromiseClient.prototype.updateAvailability =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/scheduler.SchedulerService/UpdateAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_UpdateAvailability);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.scheduler.CreateAvailabilityRequest,
 *   !proto.scheduler.CreateAvailabilityResponse>}
 */
const methodDescriptor_SchedulerService_CreateAvailability = new grpc.web.MethodDescriptor(
  '/scheduler.SchedulerService/CreateAvailability',
  grpc.web.MethodType.UNARY,
  proto.scheduler.CreateAvailabilityRequest,
  proto.scheduler.CreateAvailabilityResponse,
  /**
   * @param {!proto.scheduler.CreateAvailabilityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.scheduler.CreateAvailabilityResponse.deserializeBinary
);


/**
 * @param {!proto.scheduler.CreateAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.scheduler.CreateAvailabilityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.scheduler.CreateAvailabilityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.scheduler.SchedulerServiceClient.prototype.createAvailability =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/scheduler.SchedulerService/CreateAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_CreateAvailability,
      callback);
};


/**
 * @param {!proto.scheduler.CreateAvailabilityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.scheduler.CreateAvailabilityResponse>}
 *     Promise that resolves to the response
 */
proto.scheduler.SchedulerServicePromiseClient.prototype.createAvailability =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/scheduler.SchedulerService/CreateAvailability',
      request,
      metadata || {},
      methodDescriptor_SchedulerService_CreateAvailability);
};


module.exports = proto.scheduler;

