global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Example: if you have a containerized app exposing metrics
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:30080']

  - job_name: 'list-patient-service'
    static_configs:
      - targets: [ 'host.docker.internal:30081' ]

  - job_name: 'patient-detail-service'
    static_configs:
      - targets: [ 'host.docker.internal:30082' ]


  - job_name: 'risk-app-service'
    static_configs:
      - targets: [ 'risk-app-service:8003' ]

  - job_name: 'scheduler-service'
    static_configs:
      - targets: [ 'scheduler-service:8004' ]







