/**
 * @fileoverview gRPC-Web generated client stub for authentication
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: auth.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.authentication = require('./auth_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentication.AuthenticationClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentication.AuthenticationPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authentication.Credentials,
 *   !proto.authentication.Reply>}
 */
const methodDescriptor_Authentication_is_credential_correct = new grpc.web.MethodDescriptor(
  '/authentication.Authentication/is_credential_correct',
  grpc.web.MethodType.UNARY,
  proto.authentication.Credentials,
  proto.authentication.Reply,
  /**
   * @param {!proto.authentication.Credentials} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authentication.Reply.deserializeBinary
);


/**
 * @param {!proto.authentication.Credentials} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authentication.Reply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authentication.Reply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authentication.AuthenticationClient.prototype.is_credential_correct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authentication.Authentication/is_credential_correct',
      request,
      metadata || {},
      methodDescriptor_Authentication_is_credential_correct,
      callback);
};


/**
 * @param {!proto.authentication.Credentials} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authentication.Reply>}
 *     Promise that resolves to the response
 */
proto.authentication.AuthenticationPromiseClient.prototype.is_credential_correct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authentication.Authentication/is_credential_correct',
      request,
      metadata || {},
      methodDescriptor_Authentication_is_credential_correct);
};


module.exports = proto.authentication;

