# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0e\x61uthentication\"#\n\x0b\x43redentials\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"\x12\n\x05Reply\x12\t\n\x01x\x18\x01 \x01(\x08\x32_\n\x0e\x41uthentication\x12M\n\x15is_credential_correct\x12\x1b.authentication.Credentials\x1a\x15.authentication.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREDENTIALS']._serialized_start=30
  _globals['_CREDENTIALS']._serialized_end=65
  _globals['_REPLY']._serialized_start=67
  _globals['_REPLY']._serialized_end=85
  _globals['_AUTHENTICATION']._serialized_start=87
  _globals['_AUTHENTICATION']._serialized_end=182
# @@protoc_insertion_point(module_scope)
