# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doctor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'doctor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64octor.proto\x12\tscheduler\"\x07\n\x05\x45mpty\"u\n\x19\x43reateAvailabilityRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\t\x12\x11\n\tavailable\x18\x05 \x01(\x08\"W\n\x1a\x43reateAvailabilityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0f\x61vailability_id\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"A\n\x06\x44octor\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0especialization\x18\x03 \x01(\t\"0\n\nDoctorList\x12\"\n\x07\x64octors\x18\x01 \x03(\x0b\x32\x11.scheduler.Doctor\"\x87\x01\n\x12\x44octorAvailability\x12\x17\n\x0f\x61vailability_id\x18\x01 \x01(\x05\x12\x11\n\tdoctor_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x11\n\tavailable\x18\x06 \x01(\x08\".\n\x19\x44octorAvailabilityRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\x05\"M\n\x16\x44octorAvailabilityList\x12\x33\n\x0c\x61vailability\x18\x01 \x03(\x0b\x32\x1d.scheduler.DoctorAvailability\"G\n\x19UpdateAvailabilityRequest\x12\x17\n\x0f\x61vailability_id\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x08\"-\n\x1aUpdateAvailabilityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xeb\x02\n\x10SchedulerService\x12\x35\n\nGetDoctors\x12\x10.scheduler.Empty\x1a\x15.scheduler.DoctorList\x12Z\n\x0fGetAvailability\x12$.scheduler.DoctorAvailabilityRequest\x1a!.scheduler.DoctorAvailabilityList\x12\x61\n\x12UpdateAvailability\x12$.scheduler.UpdateAvailabilityRequest\x1a%.scheduler.UpdateAvailabilityResponse\x12\x61\n\x12\x43reateAvailability\x12$.scheduler.CreateAvailabilityRequest\x1a%.scheduler.CreateAvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doctor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_CREATEAVAILABILITYREQUEST']._serialized_start=36
  _globals['_CREATEAVAILABILITYREQUEST']._serialized_end=153
  _globals['_CREATEAVAILABILITYRESPONSE']._serialized_start=155
  _globals['_CREATEAVAILABILITYRESPONSE']._serialized_end=242
  _globals['_DOCTOR']._serialized_start=244
  _globals['_DOCTOR']._serialized_end=309
  _globals['_DOCTORLIST']._serialized_start=311
  _globals['_DOCTORLIST']._serialized_end=359
  _globals['_DOCTORAVAILABILITY']._serialized_start=362
  _globals['_DOCTORAVAILABILITY']._serialized_end=497
  _globals['_DOCTORAVAILABILITYREQUEST']._serialized_start=499
  _globals['_DOCTORAVAILABILITYREQUEST']._serialized_end=545
  _globals['_DOCTORAVAILABILITYLIST']._serialized_start=547
  _globals['_DOCTORAVAILABILITYLIST']._serialized_end=624
  _globals['_UPDATEAVAILABILITYREQUEST']._serialized_start=626
  _globals['_UPDATEAVAILABILITYREQUEST']._serialized_end=697
  _globals['_UPDATEAVAILABILITYRESPONSE']._serialized_start=699
  _globals['_UPDATEAVAILABILITYRESPONSE']._serialized_end=744
  _globals['_SCHEDULERSERVICE']._serialized_start=747
  _globals['_SCHEDULERSERVICE']._serialized_end=1110
# @@protoc_insertion_point(module_scope)
