# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import doctor_pb2 as doctor__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in doctor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDoctors = channel.unary_unary(
                '/scheduler.SchedulerService/GetDoctors',
                request_serializer=doctor__pb2.Empty.SerializeToString,
                response_deserializer=doctor__pb2.DoctorList.FromString,
                _registered_method=True)
        self.GetAvailability = channel.unary_unary(
                '/scheduler.SchedulerService/GetAvailability',
                request_serializer=doctor__pb2.DoctorAvailabilityRequest.SerializeToString,
                response_deserializer=doctor__pb2.DoctorAvailabilityList.FromString,
                _registered_method=True)
        self.UpdateAvailability = channel.unary_unary(
                '/scheduler.SchedulerService/UpdateAvailability',
                request_serializer=doctor__pb2.UpdateAvailabilityRequest.SerializeToString,
                response_deserializer=doctor__pb2.UpdateAvailabilityResponse.FromString,
                _registered_method=True)
        self.CreateAvailability = channel.unary_unary(
                '/scheduler.SchedulerService/CreateAvailability',
                request_serializer=doctor__pb2.CreateAvailabilityRequest.SerializeToString,
                response_deserializer=doctor__pb2.CreateAvailabilityResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDoctors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDoctors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoctors,
                    request_deserializer=doctor__pb2.Empty.FromString,
                    response_serializer=doctor__pb2.DoctorList.SerializeToString,
            ),
            'GetAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailability,
                    request_deserializer=doctor__pb2.DoctorAvailabilityRequest.FromString,
                    response_serializer=doctor__pb2.DoctorAvailabilityList.SerializeToString,
            ),
            'UpdateAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAvailability,
                    request_deserializer=doctor__pb2.UpdateAvailabilityRequest.FromString,
                    response_serializer=doctor__pb2.UpdateAvailabilityResponse.SerializeToString,
            ),
            'CreateAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAvailability,
                    request_deserializer=doctor__pb2.CreateAvailabilityRequest.FromString,
                    response_serializer=doctor__pb2.CreateAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDoctors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetDoctors',
            doctor__pb2.Empty.SerializeToString,
            doctor__pb2.DoctorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetAvailability',
            doctor__pb2.DoctorAvailabilityRequest.SerializeToString,
            doctor__pb2.DoctorAvailabilityList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/UpdateAvailability',
            doctor__pb2.UpdateAvailabilityRequest.SerializeToString,
            doctor__pb2.UpdateAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/CreateAvailability',
            doctor__pb2.CreateAvailabilityRequest.SerializeToString,
            doctor__pb2.CreateAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
