/**
 * @fileoverview gRPC-Web generated client stub for patient
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.1
// source: patient_detail.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.patient = require('./patient_detail_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.patient.PatientDetailServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.patient.PatientDetailServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.patient.GetPatientDetailsRequest,
 *   !proto.patient.GetPatientDetailsResponse>}
 */
const methodDescriptor_PatientDetailService_GetPatientDetails = new grpc.web.MethodDescriptor(
  '/patient.PatientDetailService/GetPatientDetails',
  grpc.web.MethodType.UNARY,
  proto.patient.GetPatientDetailsRequest,
  proto.patient.GetPatientDetailsResponse,
  /**
   * @param {!proto.patient.GetPatientDetailsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.patient.GetPatientDetailsResponse.deserializeBinary
);


/**
 * @param {!proto.patient.GetPatientDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.patient.GetPatientDetailsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.patient.GetPatientDetailsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.patient.PatientDetailServiceClient.prototype.getPatientDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/patient.PatientDetailService/GetPatientDetails',
      request,
      metadata || {},
      methodDescriptor_PatientDetailService_GetPatientDetails,
      callback);
};


/**
 * @param {!proto.patient.GetPatientDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.patient.GetPatientDetailsResponse>}
 *     Promise that resolves to the response
 */
proto.patient.PatientDetailServicePromiseClient.prototype.getPatientDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/patient.PatientDetailService/GetPatientDetails',
      request,
      metadata || {},
      methodDescriptor_PatientDetailService_GetPatientDetails);
};


module.exports = proto.patient;

