// source: patient_detail.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.patient.CKDInformation', null, global);
goog.exportSymbol('proto.patient.CVDInformation', null, global);
goog.exportSymbol('proto.patient.DiabetesInformation', null, global);
goog.exportSymbol('proto.patient.GeneralInformation', null, global);
goog.exportSymbol('proto.patient.GetPatientDetailsRequest', null, global);
goog.exportSymbol('proto.patient.GetPatientDetailsResponse', null, global);
goog.exportSymbol('proto.patient.HMODInformation', null, global);
goog.exportSymbol('proto.patient.Patient', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.GetPatientDetailsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.GetPatientDetailsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.GetPatientDetailsRequest.displayName = 'proto.patient.GetPatientDetailsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.GetPatientDetailsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.patient.GetPatientDetailsResponse.repeatedFields_, null);
};
goog.inherits(proto.patient.GetPatientDetailsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.GetPatientDetailsResponse.displayName = 'proto.patient.GetPatientDetailsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.Patient = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.Patient, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.Patient.displayName = 'proto.patient.Patient';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.GeneralInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.GeneralInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.GeneralInformation.displayName = 'proto.patient.GeneralInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.DiabetesInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.DiabetesInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.DiabetesInformation.displayName = 'proto.patient.DiabetesInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.HMODInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.HMODInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.HMODInformation.displayName = 'proto.patient.HMODInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.CKDInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.CKDInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.CKDInformation.displayName = 'proto.patient.CKDInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.patient.CVDInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.patient.CVDInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.patient.CVDInformation.displayName = 'proto.patient.CVDInformation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.GetPatientDetailsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.GetPatientDetailsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.GetPatientDetailsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GetPatientDetailsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
patientId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.GetPatientDetailsRequest}
 */
proto.patient.GetPatientDetailsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.GetPatientDetailsRequest;
  return proto.patient.GetPatientDetailsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.GetPatientDetailsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.GetPatientDetailsRequest}
 */
proto.patient.GetPatientDetailsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPatientId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.GetPatientDetailsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.GetPatientDetailsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.GetPatientDetailsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GetPatientDetailsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 patient_id = 1;
 * @return {number}
 */
proto.patient.GetPatientDetailsRequest.prototype.getPatientId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GetPatientDetailsRequest} returns this
 */
proto.patient.GetPatientDetailsRequest.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.patient.GetPatientDetailsResponse.repeatedFields_ = [2,3,4,5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.GetPatientDetailsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.GetPatientDetailsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.GetPatientDetailsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GetPatientDetailsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
patient: (f = msg.getPatient()) && proto.patient.Patient.toObject(includeInstance, f),
generalInfoList: jspb.Message.toObjectList(msg.getGeneralInfoList(),
    proto.patient.GeneralInformation.toObject, includeInstance),
diabetesInfoList: jspb.Message.toObjectList(msg.getDiabetesInfoList(),
    proto.patient.DiabetesInformation.toObject, includeInstance),
hmodInfoList: jspb.Message.toObjectList(msg.getHmodInfoList(),
    proto.patient.HMODInformation.toObject, includeInstance),
ckdInfoList: jspb.Message.toObjectList(msg.getCkdInfoList(),
    proto.patient.CKDInformation.toObject, includeInstance),
cvdInfoList: jspb.Message.toObjectList(msg.getCvdInfoList(),
    proto.patient.CVDInformation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.GetPatientDetailsResponse}
 */
proto.patient.GetPatientDetailsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.GetPatientDetailsResponse;
  return proto.patient.GetPatientDetailsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.GetPatientDetailsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.GetPatientDetailsResponse}
 */
proto.patient.GetPatientDetailsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.patient.Patient;
      reader.readMessage(value,proto.patient.Patient.deserializeBinaryFromReader);
      msg.setPatient(value);
      break;
    case 2:
      var value = new proto.patient.GeneralInformation;
      reader.readMessage(value,proto.patient.GeneralInformation.deserializeBinaryFromReader);
      msg.addGeneralInfo(value);
      break;
    case 3:
      var value = new proto.patient.DiabetesInformation;
      reader.readMessage(value,proto.patient.DiabetesInformation.deserializeBinaryFromReader);
      msg.addDiabetesInfo(value);
      break;
    case 4:
      var value = new proto.patient.HMODInformation;
      reader.readMessage(value,proto.patient.HMODInformation.deserializeBinaryFromReader);
      msg.addHmodInfo(value);
      break;
    case 5:
      var value = new proto.patient.CKDInformation;
      reader.readMessage(value,proto.patient.CKDInformation.deserializeBinaryFromReader);
      msg.addCkdInfo(value);
      break;
    case 6:
      var value = new proto.patient.CVDInformation;
      reader.readMessage(value,proto.patient.CVDInformation.deserializeBinaryFromReader);
      msg.addCvdInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.GetPatientDetailsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.GetPatientDetailsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.GetPatientDetailsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GetPatientDetailsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatient();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.patient.Patient.serializeBinaryToWriter
    );
  }
  f = message.getGeneralInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.patient.GeneralInformation.serializeBinaryToWriter
    );
  }
  f = message.getDiabetesInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.patient.DiabetesInformation.serializeBinaryToWriter
    );
  }
  f = message.getHmodInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.patient.HMODInformation.serializeBinaryToWriter
    );
  }
  f = message.getCkdInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.patient.CKDInformation.serializeBinaryToWriter
    );
  }
  f = message.getCvdInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.patient.CVDInformation.serializeBinaryToWriter
    );
  }
};


/**
 * optional Patient patient = 1;
 * @return {?proto.patient.Patient}
 */
proto.patient.GetPatientDetailsResponse.prototype.getPatient = function() {
  return /** @type{?proto.patient.Patient} */ (
    jspb.Message.getWrapperField(this, proto.patient.Patient, 1));
};


/**
 * @param {?proto.patient.Patient|undefined} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setPatient = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearPatient = function() {
  return this.setPatient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.patient.GetPatientDetailsResponse.prototype.hasPatient = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated GeneralInformation general_info = 2;
 * @return {!Array<!proto.patient.GeneralInformation>}
 */
proto.patient.GetPatientDetailsResponse.prototype.getGeneralInfoList = function() {
  return /** @type{!Array<!proto.patient.GeneralInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.patient.GeneralInformation, 2));
};


/**
 * @param {!Array<!proto.patient.GeneralInformation>} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setGeneralInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.patient.GeneralInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.patient.GeneralInformation}
 */
proto.patient.GetPatientDetailsResponse.prototype.addGeneralInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.patient.GeneralInformation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearGeneralInfoList = function() {
  return this.setGeneralInfoList([]);
};


/**
 * repeated DiabetesInformation diabetes_info = 3;
 * @return {!Array<!proto.patient.DiabetesInformation>}
 */
proto.patient.GetPatientDetailsResponse.prototype.getDiabetesInfoList = function() {
  return /** @type{!Array<!proto.patient.DiabetesInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.patient.DiabetesInformation, 3));
};


/**
 * @param {!Array<!proto.patient.DiabetesInformation>} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setDiabetesInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.patient.DiabetesInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.patient.DiabetesInformation}
 */
proto.patient.GetPatientDetailsResponse.prototype.addDiabetesInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.patient.DiabetesInformation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearDiabetesInfoList = function() {
  return this.setDiabetesInfoList([]);
};


/**
 * repeated HMODInformation hmod_info = 4;
 * @return {!Array<!proto.patient.HMODInformation>}
 */
proto.patient.GetPatientDetailsResponse.prototype.getHmodInfoList = function() {
  return /** @type{!Array<!proto.patient.HMODInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.patient.HMODInformation, 4));
};


/**
 * @param {!Array<!proto.patient.HMODInformation>} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setHmodInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.patient.HMODInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.patient.HMODInformation}
 */
proto.patient.GetPatientDetailsResponse.prototype.addHmodInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.patient.HMODInformation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearHmodInfoList = function() {
  return this.setHmodInfoList([]);
};


/**
 * repeated CKDInformation ckd_info = 5;
 * @return {!Array<!proto.patient.CKDInformation>}
 */
proto.patient.GetPatientDetailsResponse.prototype.getCkdInfoList = function() {
  return /** @type{!Array<!proto.patient.CKDInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.patient.CKDInformation, 5));
};


/**
 * @param {!Array<!proto.patient.CKDInformation>} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setCkdInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.patient.CKDInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.patient.CKDInformation}
 */
proto.patient.GetPatientDetailsResponse.prototype.addCkdInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.patient.CKDInformation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearCkdInfoList = function() {
  return this.setCkdInfoList([]);
};


/**
 * repeated CVDInformation cvd_info = 6;
 * @return {!Array<!proto.patient.CVDInformation>}
 */
proto.patient.GetPatientDetailsResponse.prototype.getCvdInfoList = function() {
  return /** @type{!Array<!proto.patient.CVDInformation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.patient.CVDInformation, 6));
};


/**
 * @param {!Array<!proto.patient.CVDInformation>} value
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
*/
proto.patient.GetPatientDetailsResponse.prototype.setCvdInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.patient.CVDInformation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.patient.CVDInformation}
 */
proto.patient.GetPatientDetailsResponse.prototype.addCvdInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.patient.CVDInformation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.patient.GetPatientDetailsResponse} returns this
 */
proto.patient.GetPatientDetailsResponse.prototype.clearCvdInfoList = function() {
  return this.setCvdInfoList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.Patient.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.Patient.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.Patient} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.Patient.toObject = function(includeInstance, msg) {
  var f, obj = {
patientId: jspb.Message.getFieldWithDefault(msg, 1, 0),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
age: jspb.Message.getFieldWithDefault(msg, 3, 0),
gender: jspb.Message.getFieldWithDefault(msg, 4, 0),
diabetes: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
hmod: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
ckd: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
cvd: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
chd: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
riskCategoryId: jspb.Message.getFieldWithDefault(msg, 10, ""),
riskDescription: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.Patient}
 */
proto.patient.Patient.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.Patient;
  return proto.patient.Patient.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.Patient} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.Patient}
 */
proto.patient.Patient.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAge(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGender(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDiabetes(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHmod(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCkd(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCvd(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setChd(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setRiskCategoryId(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setRiskDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.Patient.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.Patient.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.Patient} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.Patient.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAge();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getGender();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getDiabetes();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getHmod();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getCkd();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getCvd();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getChd();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getRiskCategoryId();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getRiskDescription();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional int32 patient_id = 1;
 * @return {number}
 */
proto.patient.Patient.prototype.getPatientId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.patient.Patient.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 age = 3;
 * @return {number}
 */
proto.patient.Patient.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setAge = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 gender = 4;
 * @return {number}
 */
proto.patient.Patient.prototype.getGender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setGender = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional float diabetes = 5;
 * @return {number}
 */
proto.patient.Patient.prototype.getDiabetes = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setDiabetes = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float hmod = 6;
 * @return {number}
 */
proto.patient.Patient.prototype.getHmod = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setHmod = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float ckd = 7;
 * @return {number}
 */
proto.patient.Patient.prototype.getCkd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setCkd = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float cvd = 8;
 * @return {number}
 */
proto.patient.Patient.prototype.getCvd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setCvd = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float chd = 9;
 * @return {number}
 */
proto.patient.Patient.prototype.getChd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setChd = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional string risk_category_id = 10;
 * @return {string}
 */
proto.patient.Patient.prototype.getRiskCategoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setRiskCategoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string risk_description = 11;
 * @return {string}
 */
proto.patient.Patient.prototype.getRiskDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.Patient} returns this
 */
proto.patient.Patient.prototype.setRiskDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.GeneralInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.GeneralInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.GeneralInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GeneralInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
infoId: jspb.Message.getFieldWithDefault(msg, 1, 0),
pid: jspb.Message.getFieldWithDefault(msg, 2, 0),
avgDailySteps: jspb.Message.getFieldWithDefault(msg, 3, 0),
hdl: jspb.Message.getFieldWithDefault(msg, 4, 0),
ldl: jspb.Message.getFieldWithDefault(msg, 5, 0),
cholesterol: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
cacs: jspb.Message.getFieldWithDefault(msg, 7, 0),
restingPulse: jspb.Message.getFieldWithDefault(msg, 8, 0),
testDate: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.GeneralInformation}
 */
proto.patient.GeneralInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.GeneralInformation;
  return proto.patient.GeneralInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.GeneralInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.GeneralInformation}
 */
proto.patient.GeneralInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInfoId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAvgDailySteps(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHdl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLdl(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCholesterol(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCacs(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRestingPulse(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.GeneralInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.GeneralInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.GeneralInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.GeneralInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfoId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAvgDailySteps();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getHdl();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLdl();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getCholesterol();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getCacs();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getRestingPulse();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getTestDate();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional int32 info_id = 1;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getInfoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setInfoId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pid = 2;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 avg_daily_steps = 3;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getAvgDailySteps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setAvgDailySteps = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 hdl = 4;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getHdl = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setHdl = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 ldl = 5;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getLdl = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setLdl = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float cholesterol = 6;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getCholesterol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setCholesterol = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int32 cacs = 7;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getCacs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setCacs = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 resting_pulse = 8;
 * @return {number}
 */
proto.patient.GeneralInformation.prototype.getRestingPulse = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setRestingPulse = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string test_date = 9;
 * @return {string}
 */
proto.patient.GeneralInformation.prototype.getTestDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.GeneralInformation} returns this
 */
proto.patient.GeneralInformation.prototype.setTestDate = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.DiabetesInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.DiabetesInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.DiabetesInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.DiabetesInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
diabetesId: jspb.Message.getFieldWithDefault(msg, 1, 0),
pid: jspb.Message.getFieldWithDefault(msg, 2, 0),
fbg: jspb.Message.getFieldWithDefault(msg, 3, 0),
hba1c: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
testDate: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.DiabetesInformation}
 */
proto.patient.DiabetesInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.DiabetesInformation;
  return proto.patient.DiabetesInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.DiabetesInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.DiabetesInformation}
 */
proto.patient.DiabetesInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDiabetesId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFbg(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHba1c(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.DiabetesInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.DiabetesInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.DiabetesInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.DiabetesInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDiabetesId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFbg();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getHba1c();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getTestDate();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int32 diabetes_id = 1;
 * @return {number}
 */
proto.patient.DiabetesInformation.prototype.getDiabetesId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.DiabetesInformation} returns this
 */
proto.patient.DiabetesInformation.prototype.setDiabetesId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pid = 2;
 * @return {number}
 */
proto.patient.DiabetesInformation.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.DiabetesInformation} returns this
 */
proto.patient.DiabetesInformation.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 fbg = 3;
 * @return {number}
 */
proto.patient.DiabetesInformation.prototype.getFbg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.DiabetesInformation} returns this
 */
proto.patient.DiabetesInformation.prototype.setFbg = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float hba1c = 4;
 * @return {number}
 */
proto.patient.DiabetesInformation.prototype.getHba1c = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.DiabetesInformation} returns this
 */
proto.patient.DiabetesInformation.prototype.setHba1c = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string test_date = 5;
 * @return {string}
 */
proto.patient.DiabetesInformation.prototype.getTestDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.DiabetesInformation} returns this
 */
proto.patient.DiabetesInformation.prototype.setTestDate = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.HMODInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.HMODInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.HMODInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.HMODInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
hmodId: jspb.Message.getFieldWithDefault(msg, 1, 0),
pid: jspb.Message.getFieldWithDefault(msg, 2, 0),
lvMass: jspb.Message.getFieldWithDefault(msg, 3, 0),
microalbuminuria: jspb.Message.getFieldWithDefault(msg, 4, 0),
pwv: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
abi: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
testDate: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.HMODInformation}
 */
proto.patient.HMODInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.HMODInformation;
  return proto.patient.HMODInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.HMODInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.HMODInformation}
 */
proto.patient.HMODInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHmodId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLvMass(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMicroalbuminuria(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPwv(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAbi(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.HMODInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.HMODInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.HMODInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.HMODInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHmodId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLvMass();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMicroalbuminuria();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPwv();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getAbi();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getTestDate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional int32 hmod_id = 1;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getHmodId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setHmodId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pid = 2;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 lv_mass = 3;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getLvMass = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setLvMass = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 microalbuminuria = 4;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getMicroalbuminuria = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setMicroalbuminuria = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional float pwv = 5;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getPwv = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setPwv = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float abi = 6;
 * @return {number}
 */
proto.patient.HMODInformation.prototype.getAbi = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setAbi = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string test_date = 7;
 * @return {string}
 */
proto.patient.HMODInformation.prototype.getTestDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.HMODInformation} returns this
 */
proto.patient.HMODInformation.prototype.setTestDate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.CKDInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.CKDInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.CKDInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.CKDInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
ckdId: jspb.Message.getFieldWithDefault(msg, 1, 0),
pid: jspb.Message.getFieldWithDefault(msg, 2, 0),
serumCreatinine: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
egfr: jspb.Message.getFieldWithDefault(msg, 4, 0),
uacr: jspb.Message.getFieldWithDefault(msg, 5, 0),
testDate: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.CKDInformation}
 */
proto.patient.CKDInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.CKDInformation;
  return proto.patient.CKDInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.CKDInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.CKDInformation}
 */
proto.patient.CKDInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCkdId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSerumCreatinine(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEgfr(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUacr(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.CKDInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.CKDInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.CKDInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.CKDInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCkdId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSerumCreatinine();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getEgfr();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getUacr();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getTestDate();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int32 ckd_id = 1;
 * @return {number}
 */
proto.patient.CKDInformation.prototype.getCkdId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setCkdId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pid = 2;
 * @return {number}
 */
proto.patient.CKDInformation.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float serum_creatinine = 3;
 * @return {number}
 */
proto.patient.CKDInformation.prototype.getSerumCreatinine = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setSerumCreatinine = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 egfr = 4;
 * @return {number}
 */
proto.patient.CKDInformation.prototype.getEgfr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setEgfr = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 uacr = 5;
 * @return {number}
 */
proto.patient.CKDInformation.prototype.getUacr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setUacr = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string test_date = 6;
 * @return {string}
 */
proto.patient.CKDInformation.prototype.getTestDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.CKDInformation} returns this
 */
proto.patient.CKDInformation.prototype.setTestDate = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.patient.CVDInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.patient.CVDInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.patient.CVDInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.CVDInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
cvdId: jspb.Message.getFieldWithDefault(msg, 1, 0),
pid: jspb.Message.getFieldWithDefault(msg, 2, 0),
bp: jspb.Message.getFieldWithDefault(msg, 3, ""),
smoking: jspb.Message.getFieldWithDefault(msg, 4, 0),
testDate: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.patient.CVDInformation}
 */
proto.patient.CVDInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.patient.CVDInformation;
  return proto.patient.CVDInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.patient.CVDInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.patient.CVDInformation}
 */
proto.patient.CVDInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCvdId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBp(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSmoking(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTestDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.patient.CVDInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.patient.CVDInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.patient.CVDInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.patient.CVDInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCvdId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getBp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSmoking();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getTestDate();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int32 cvd_id = 1;
 * @return {number}
 */
proto.patient.CVDInformation.prototype.getCvdId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CVDInformation} returns this
 */
proto.patient.CVDInformation.prototype.setCvdId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 pid = 2;
 * @return {number}
 */
proto.patient.CVDInformation.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CVDInformation} returns this
 */
proto.patient.CVDInformation.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string bp = 3;
 * @return {string}
 */
proto.patient.CVDInformation.prototype.getBp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.CVDInformation} returns this
 */
proto.patient.CVDInformation.prototype.setBp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 smoking = 4;
 * @return {number}
 */
proto.patient.CVDInformation.prototype.getSmoking = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.patient.CVDInformation} returns this
 */
proto.patient.CVDInformation.prototype.setSmoking = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string test_date = 5;
 * @return {string}
 */
proto.patient.CVDInformation.prototype.getTestDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.patient.CVDInformation} returns this
 */
proto.patient.CVDInformation.prototype.setTestDate = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.patient);
